# Generated by Django 2.1.4 on 2020-01-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('wxNumber', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '联系信息',
                'verbose_name_plural': '联系信息',
                'ordering': ['name', 'id'],
            },
        ),
    ]
